export enum RabbitMQ {
  RegisterQueue = "registers",
}


export enum RegisterMSG {
  CREATE = 'CREATE_REGISTER',
  FIND_ALL = 'FIND_REGISTERS',
  FIND_ONE = 'FIND_REGISTER',
  UPDATE = 'UPDATE_REGISTER',
  DELETE = 'DELETE_REGISTER',
  ADD_USER = 'ADD_REGISTER_USER',
  UPDATE_PARTIAL = "UPDATE_PARTIAL",
  FIND_SCHEDULE = "FIND_SCHEDULE",
  FIND_SCHEDULE_ID = "FIND_SCHEDULE_ID",

}
